---
name: Checks

on: [push]

jobs:
  test-lint:
    mames: Test and Lint
    runs on: ubuntu-20.04
    steps:
      - name: Test and Lint
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: action/checkout@v2
      - name: Test 
        uses: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint 
        uses: docker-compose run --rm app sh -c "flake8"